.dockerignore, .github/workflows/ci.yaml, .github/workflows/slack-notify.yaml, .gitignore, .kres.yaml, Makefile, Pkgfile, hack/release.sh, hack/release.toml, hack/scripts/generate-digests.sh, hack/scripts/sign-images.sh, internal/overlays/overlays.yaml, internal/overlays/pkg.yaml
=> feat: add overlays

.conform.yaml, .dockerignore, CHANGELOG.md, hack/release.toml
This is the official v1.7.0-alpha.1 release.
=> release(v1.7.0-alpha.1): prepare release

README.md, internal/overlays/overlays.yaml
Add documentation on overlays.
Also pull in the new [Rock4C+ SBC](https://github.com/siderolabs/sbc-rockchip/pull/5).
=> docs: add overlays docs

CHANGELOG.md, hack/release.toml
This is the official v1.7.0 release.
=> release(v1.7.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.1 release.
=> release(v1.7.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.2 release.
=> release(v1.7.2): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.3 release.
=> release(v1.7.3): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.4 release.
=> release(v1.7.4): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.5 release.
=> release(v1.7.5): prepare release

.github/workflows/ci.yaml, Makefile, README.md, hack/release.toml, internal/overlays/overlays.yaml
* https://github.com/siderolabs/sbc-raspberrypi/releases/tag/v0.1.0-beta.1
* https://github.com/siderolabs/sbc-rockchip/releases/tag/v0.1.0-beta.2
=> feat: bump overlays rockchip & raspberrypi

CHANGELOG.md, hack/release.toml
This is the official v1.7.6 release.
=> release(v1.7.6): prepare release

.github/workflows/ci.yaml, CHANGELOG.md, README.md, hack/release.sh, internal/overlays/overlays.yaml
This is the official v1.8.0-alpha.2 release.
=> release(v1.8.0-alpha.2): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.7.7 release.
=> release(v1.7.7): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.8.1 release.
=> release(v1.8.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.9.0-alpha.0 release.
=> release(v1.9.0-alpha.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.8.2 release.
=> release(v1.8.2): prepare release

CHANGELOG.md
This is the official v1.9.0-alpha.1 release.
=> release(v1.9.0-alpha.1): prepare release

CHANGELOG.md
This is the official v1.9.0-alpha.2 release.
=> release(v1.9.0-alpha.2): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.8.3 release.
=> release(v1.8.3): prepare release

CHANGELOG.md
This is the official v1.9.0-alpha.3 release.
=> release(v1.9.0-alpha.3): prepare release

CHANGELOG.md
This is the official v1.9.0-beta.0 release.
=> release(v1.9.0-beta.0): prepare release

internal/overlays/overlays.yaml
See https://github.com/siderolabs/sbc-rockchip/releases/tag/v0.1.1
=> feat: update sbc-rockchip to v0.1.1

CHANGELOG.md
This is the official v1.9.0-beta.1 release.
=> release(v1.9.0-beta.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.9.0 release.
=> release(v1.9.0): prepare release

internal/overlays/overlays.yaml
See https://github.com/siderolabs/sbc-raspberrypi/releases/tag/v0.1.1
=> feat: update sbc-raspberrypi to v0.1.1

CHANGELOG.md, hack/release.toml
This is the official v1.9.1 release.
=> release(v1.9.1): prepare release

.github/renovate.json, .github/workflows/ci.yaml, .github/workflows/slack-notify.yaml, README.md, internal/overlays/overlays.yaml
Add Radxa Rock5B overlay.
Signed-off-by: Noel Georgi <git@frezbo.dev>
(cherry picked from commit 833e595ef2b19758a4f63f9dfb3707b0285a85e8)
=> backport: feat: add radxa rock5b overlay

CHANGELOG.md, hack/release.toml
This is the official v1.9.2 release.
=> release(v1.9.2): prepare release

internal/overlays/overlays.yaml
=> feat: update rockpi to 0.1.3

internal/overlays/overlays.yaml
Contains a small fix for the watchdog.
=> feat: bump raspberrypi to 0.1.2

CHANGELOG.md
This is the official v1.9.3 release.
=> release(v1.9.3): prepare release

internal/overlays/overlays.yaml
See https://github.com/siderolabs/sbc-raspberrypi/releases/tag/v0.1.3
=> feat: update sbc-raspberrypi to v0.1.3

CHANGELOG.md, hack/release.toml
This is the official v1.9.4 release.
=> release(v1.9.4): prepare release

.github/workflows/ci.yaml, Makefile
Use same buildkit for all builds.
=> chore: unify buildkits

.github/workflows/ci.yaml, CHANGELOG.md, Makefile, hack/release.toml
This is the official v1.9.5 release.
=> release(v1.9.5): prepare release

README.md, internal/overlays/overlays.yaml
Bring in new boards and update overlay references.
=> feat: bring in new boards

CHANGELOG.md, hack/release.toml
This is the official v1.10.0 release.
=> release(v1.10.0): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.9.6 release.
=> release(v1.9.6): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.10.1 release.
=> release(v1.10.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.10.3 release.
=> release(v1.10.3): prepare release

CHANGELOG.md
This is the official v1.11.0-alpha.3 release.
=> release(v1.11.0-alpha.3): prepare release

.github/renovate.json, .github/workflows/ci.yaml, .github/workflows/lock.yml, .github/workflows/slack-notify.yaml, .github/workflows/stale.yml, Makefile, Pkgfile
Rekres and update dependencies.
=> chore: rekres and update

CHANGELOG.md, hack/release.toml
This is the official v1.10.6 release.
=> release(v1.10.6): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.10.7 release.
=> release(v1.10.7): prepare release

CHANGELOG.md, hack/release.toml
This is the official v1.11.0 release.
=> release(v1.11.0): prepare release
