hack/scripts/sign-images.sh

An overlay might support multiple SBC's from a single image. No point in trying to sign an already signed image. So select images to sign unique by image name.

fix: image signing script.

---

CHANGELOG.md

This is the official v1.7.0-beta.0 release.

release(v1.7.0-beta.0): prepare release

---

internal/overlays/overlays.yaml

Brings in a fix https://github.com/siderolabs/sbc-rockchip/issues/10

feat: update sbc-rockchip to v0.1.0-beta.1

---

internal/overlays/overlays.yaml

Brings in a fix https://github.com/siderolabs/sbc-rockchip/issues/10
(cherry picked from commit https://github.com/siderolabs/overlays/commit/37c057526a1c3cab8cce067fb767c68711f219d5)

backport: update sbc-rockchip to v0.1.0-beta.1

---

CHANGELOG.md

This is the official v1.7.0-beta.1 release.

release(v1.7.0-beta.1): prepare release

---

CHANGELOG.md
hack/release.toml

This is the official v1.8.0-alpha.0 release.

release(v1.8.0-alpha.0): prepare release

---

CHANGELOG.md

This is the official v1.8.0-alpha.1 release.

release(v1.8.0-alpha.1): prepare release

---

CHANGELOG.md

This is the official v1.8.0-beta.1 release.

release(v1.8.0-beta.1): prepare release

---

CHANGELOG.md
hack/release.toml

This is the official v1.8.0 release.

release(v1.8.0): prepare release

---

internal/overlays/overlays.yaml

See https://github.com/siderolabs/sbc-rockchip/releases/tag/v0.1.1
(cherry picked from commit 274a083215c43e60a3d39c6620682c09875b2691)

feat: update sbc-rockchip to v0.1.1

---

CHANGELOG.md
hack/release.toml

This is the official v1.10.0-alpha.0 release.

release(v1.10.0-alpha.0): prepare release

---

internal/overlays/overlays.yaml

See https://github.com/siderolabs/sbc-raspberrypi/releases/tag/v0.1.1
(cherry picked from commit 33050d303f76cbe3d19342e51238cf7f88b3e962)

backports: feat: update sbc-raspberrypi to v0.1.1

---

.conform.yaml
.kres.yaml
hack/release.toml
internal/overlays/overlays.yaml

backports: for v1.9.3

---

CHANGELOG.md

This is the official v1.10.0-alpha.1 release.

release(v1.10.0-alpha.1): prepare release

---

internal/overlays/overlays.yaml

See https://github.com/siderolabs/sbc-raspberrypi/releases/tag/v0.1.3
(cherry picked from commit f657517ce9c5bc7b3a2cf9b11352d87c3a994f83)

backport: feat: update sbc-raspberrypi to v0.1.3

---

CHANGELOG.md

This is the official v1.10.0-alpha.2 release.

release(v1.10.0-alpha.2): prepare release

---

CHANGELOG.md

This is the official v1.10.0-beta.0 release.

release(v1.10.0-beta.0): prepare release

---

CHANGELOG.md
hack/release.toml

This is the official v1.11.0-alpha.0 release.

release(v1.11.0-alpha.0): prepare release

---

CHANGELOG.md

This is the official v1.11.0-beta.0 release.

release(v1.11.0-beta.0): prepare release

---

CHANGELOG.md

This is the official v1.11.0-beta.1 release.

release(v1.11.0-beta.1): prepare release
